services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankadsapi-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: bankadsapi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bankadsapi-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo_data:
